<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\template.targets" />

	<ItemGroup>
	  <ProjectReference Include="..\LazyAPI\LazyAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MonoMod.RuntimeDetour" Version="25.2.3" />
	</ItemGroup>

	<PropertyGroup>
	  <EmbedNuGetDlls>MonoMod.RuntimeDetour.dll;MonoMod.Core.dll;MonoMod.Utils.dll;MonoMod.ILHelpers.dll;MonoMod.Backports.dll;Mono.Cecil.dll;Mono.Cecil.Mdb.dll;Mono.Cecil.Pdb.dll;Mono.Cecil.Rocks.dll</EmbedNuGetDlls>
	</PropertyGroup>

</Project>
