using Terraria.ID;

namespace RandomFishingLoot;

public sealed partial class RandomFishingLoot
{
    private static FishingLootConfig BuildDefaultConfig()
    {
        return new FishingLootConfig
        {
            Version = 3,
            Notes =
            [
                "Mode 支持 progression_items 和 random_npcs。当前默认是 progression_items，按 Boss 进度替换渔获。",
                "random_npcs 模式会从全部可用 NPC 里抽生物，可用 RandomNpc 控制是否包含 Boss、友好生物、城镇 NPC，以及替换概率。",
                "这是一套按 Boss/进度阶段解锁的渔获表。progression_items 模式会使用当前已解锁的最高阶段，再叠加 AlwaysAvailable 常驻基础池。",
                "默认只放材料、工具、药水、召唤物和推进流程所需道具，不放武器、法杖、弓枪、爆炸物等直接战斗武器。",
                "如果某个条目是武器，插件会在加载时自动跳过。",
                "ItemId 使用 Terraria ItemID。MinStack/MaxStack 是每次钓上来时的数量区间。",
                "AllowQuestFish 为 true 时，玩家处于渔夫任务中会按原版 uncommon 概率钓到当前任务鱼，不再被自定义渔获表完全覆盖。",
                "AllowCrates 为 true 时，原版宝匣（木匣、铁匣、金匣及各生物群系匣）保留，不被自定义渔获表替换。",
                "修改后使用 /fishrand reload 热重载，/fishrand sample 12 可预览当前阶段池。"
            ],
            Enabled = true,
            Mode = "progression_items",
            AnnounceToPlayer = false,
            AllowQuestFish = true,
            AllowCrates = true,
            AlwaysAvailable =
            [
                E(ItemID.Wood, 8, 30, 120),
                E(ItemID.StoneBlock, 8, 30, 150),
                E(ItemID.DirtBlock, 7, 20, 80),
                E(ItemID.Gel, 7, 15, 60),
                E(ItemID.Torch, 7, 10, 50),
                E(ItemID.Rope, 6, 15, 60),
                E(ItemID.Bottle, 4, 2, 12),
                E(ItemID.BottledWater, 4, 2, 12),
                E(ItemID.Worm, 4, 2, 8),
                E(ItemID.ApprenticeBait, 4, 2, 6),
                E(ItemID.JourneymanBait, 3, 1, 4),
                E(ItemID.FishingPotion, 3, 1, 2),
                E(ItemID.SonarPotion, 3, 1, 2),
                E(ItemID.CratePotion, 2, 1, 2),
                E(ItemID.RecallPotion, 5, 1, 3),
                E(ItemID.HealingPotion, 5, 2, 8),
                E(ItemID.MiningPotion, 3, 1, 2),
                E(ItemID.SpelunkerPotion, 3, 1, 2),
                E(ItemID.SwiftnessPotion, 3, 1, 2),
                E(ItemID.IronskinPotion, 3, 1, 2),
                E(ItemID.Feather, 3, 1, 4)
            ],
            Stages =
            [
                Stage("bootstrap", "开荒", "开局到克眼前，补基础矿、早期功能饰品和起步资源。",
                    new UnlockConditions { NotDefeated = ["eye"] },
                    E(ItemID.CopperOre, 6, 12, 30),
                    E(ItemID.TinOre, 6, 12, 30),
                    E(ItemID.IronOre, 6, 10, 24),
                    E(ItemID.LeadOre, 6, 10, 24),
                    E(ItemID.SilverOre, 5, 8, 20),
                    E(ItemID.TungstenOre, 5, 8, 20),
                    E(ItemID.GoldOre, 4, 6, 16),
                    E(ItemID.PlatinumOre, 4, 6, 16),
                    E(ItemID.Lens, 5, 2, 6),
                    E(ItemID.SuspiciousLookingEye, 2),
                    E(ItemID.FallenStar, 4, 1, 4),
                    E(ItemID.LifeCrystal, 2),
                    E(ItemID.IronPickaxe, 1),
                    E(ItemID.GoldPickaxe, 1),
                    E(ItemID.BugNet, 2),
                    E(ItemID.CloudinaBottle, 1),
                    E(ItemID.HermesBoots, 1),
                    E(ItemID.MagicMirror, 1),
                    E(ItemID.RegenerationPotion, 3, 1, 3),
                    E(ItemID.ShinePotion, 3, 1, 3),
                    E(ItemID.NightOwlPotion, 2, 1, 2),
                    E(ItemID.GillsPotion, 2, 1, 2),
                    E(ItemID.BuilderPotion, 2, 1, 2)),

                Stage("preevil", "邪恶矿阶段", "克眼后到世吞/克脑前，补召唤物和邪恶矿。",
                    new UnlockConditions { Defeated = ["eye"], NotDefeated = ["evilboss"] },
                    E(ItemID.DemoniteOre, 6, 12, 30),
                    E(ItemID.CrimtaneOre, 6, 12, 30),
                    E(ItemID.WormFood, 2),
                    E(ItemID.BloodySpine, 2),
                    E(ItemID.RottenChunk, 5, 3, 8),
                    E(ItemID.Vertebrae, 5, 3, 8),
                    E(ItemID.VilePowder, 3, 2, 6),
                    E(ItemID.ViciousPowder, 3, 2, 6),
                    E(ItemID.Meteorite, 4, 15, 35),
                    E(ItemID.Extractinator, 1),
                    E(ItemID.BandofRegeneration, 1),
                    E(ItemID.Hook, 2, 1, 2),
                    E(ItemID.GravitationPotion, 2, 1, 2),
                    E(ItemID.HunterPotion, 2, 1, 2),
                    E(ItemID.BattlePotion, 2, 1, 2)),

                Stage("prehardmode", "困难前后段", "邪恶 Boss 后到血肉墙前，补地牢、丛林和下界推进物资。",
                    new UnlockConditions { Defeated = ["evilboss"], NotDefeated = ["wof"] },
                    E(ItemID.ShadowScale, 5, 5, 14),
                    E(ItemID.TissueSample, 5, 5, 14),
                    E(ItemID.Hellstone, 6, 20, 45),
                    E(ItemID.Obsidian, 5, 12, 30),
                    E(ItemID.Hellforge, 1),
                    E(ItemID.JungleSpores, 4, 4, 12),
                    E(ItemID.Stinger, 4, 4, 10),
                    E(ItemID.Vine, 3, 1, 3),
                    E(ItemID.BeeWax, 3, 3, 10),
                    E(ItemID.GuideVoodooDoll, 2),
                    E(ItemID.Bone, 5, 20, 50),
                    E(ItemID.Cobweb, 5, 20, 60),
                    E(ItemID.Book, 3, 4, 10),
                    E(ItemID.ShadowKey, 1),
                    E(ItemID.NightmarePickaxe, 1),
                    E(ItemID.DeathbringerPickaxe, 1),
                    E(ItemID.MoltenPickaxe, 1),
                    E(ItemID.ObsidianSkinPotion, 3, 1, 3),
                    E(ItemID.WaterWalkingPotion, 2, 1, 2),
                    E(ItemID.GravitationPotion, 2, 1, 2),
                    E(ItemID.HeartreachPotion, 2, 1, 2)),

                Stage("hardmode", "困难模式开局", "血肉墙后到第一只机械 Boss 前，补三矿、魂和机械召唤。",
                    new UnlockConditions { Defeated = ["wof"], NotDefeated = ["anymech"] },
                    E(ItemID.CobaltOre, 6, 20, 60),
                    E(ItemID.PalladiumOre, 6, 20, 60),
                    E(ItemID.MythrilOre, 5, 18, 48),
                    E(ItemID.OrichalcumOre, 5, 18, 48),
                    E(ItemID.AdamantiteOre, 4, 15, 36),
                    E(ItemID.TitaniumOre, 4, 15, 36),
                    E(ItemID.CrystalShard, 4, 6, 18),
                    E(ItemID.SoulofLight, 5, 5, 14),
                    E(ItemID.SoulofNight, 5, 5, 14),
                    E(ItemID.PixieDust, 4, 6, 18),
                    E(ItemID.CursedFlame, 3, 5, 12),
                    E(ItemID.Ichor, 3, 5, 12),
                    E(ItemID.MechanicalEye, 2),
                    E(ItemID.MechanicalWorm, 2),
                    E(ItemID.MechanicalSkull, 2),
                    E(ItemID.SoulofFlight, 2, 5, 14),
                    E(ItemID.CobaltPickaxe, 1),
                    E(ItemID.PalladiumPickaxe, 1),
                    E(ItemID.MythrilPickaxe, 1),
                    E(ItemID.OrichalcumPickaxe, 1),
                    E(ItemID.AdamantitePickaxe, 1),
                    E(ItemID.TitaniumPickaxe, 1),
                    E(ItemID.MythrilAnvil, 1),
                    E(ItemID.OrichalcumAnvil, 1),
                    E(ItemID.AdamantiteForge, 1),
                    E(ItemID.TitaniumForge, 1),
                    E(ItemID.GreaterHealingPotion, 4, 3, 8),
                    E(ItemID.GreaterManaPotion, 3, 3, 8),
                    E(ItemID.EndurancePotion, 2, 1, 2),
                    E(ItemID.LifeforcePotion, 2, 1, 2),
                    E(ItemID.WrathPotion, 2, 1, 2),
                    E(ItemID.RagePotion, 2, 1, 2)),

                Stage("postmech", "任意机械 Boss 后", "任意机械 Boss 后到全部机械 Boss 前，补神圣锭、生命果和战斗药水。",
                    new UnlockConditions { Defeated = ["anymech"], NotDefeated = ["allmechs"] },
                    E(ItemID.HallowedBar, 6, 10, 22),
                    E(ItemID.LifeFruit, 3, 1, 3),
                    E(ItemID.GreaterHealingPotion, 4, 4, 10),
                    E(ItemID.EndurancePotion, 3, 1, 3),
                    E(ItemID.LifeforcePotion, 2, 1, 2)),

                Stage("postallmechs", "机械三王后", "全部机械 Boss 后到世纪之花前，解锁三魂、叶绿矿和神圣级采掘工具。",
                    new UnlockConditions { Defeated = ["allmechs"], NotDefeated = ["plantera"] },
                    E(ItemID.HallowedBar, 6, 12, 28),
                    E(ItemID.ChlorophyteOre, 6, 18, 40),
                    E(ItemID.SoulofMight, 4, 5, 14),
                    E(ItemID.SoulofSight, 4, 5, 14),
                    E(ItemID.SoulofFright, 4, 5, 14),
                    E(ItemID.LifeFruit, 3, 1, 4),
                    E(ItemID.Drax, 1),
                    E(ItemID.PickaxeAxe, 1),
                    E(ItemID.GreaterHealingPotion, 4, 5, 12),
                    E(ItemID.SpelunkerPotion, 3, 1, 3)),

                Stage("postplantera", "世纪之花后", "世纪之花后到石巨人前，补地牢灵气、神庙电池和高阶恢复。",
                    new UnlockConditions { Defeated = ["plantera"], NotDefeated = ["golem"] },
                    E(ItemID.Ectoplasm, 6, 6, 20),
                    E(ItemID.LihzahrdPowerCell, 3, 1, 3),
                    E(ItemID.TurtleShell, 2, 1, 3),
                    E(ItemID.SpectreBar, 4, 5, 15),
                    E(ItemID.ShroomiteBar, 4, 5, 15),
                    E(ItemID.ChlorophytePickaxe, 1),
                    E(ItemID.ChlorophyteDrill, 1),
                    E(ItemID.GreaterHealingPotion, 4, 5, 15),
                    E(ItemID.GreaterManaPotion, 4, 5, 15),
                    E(ItemID.EndurancePotion, 3, 1, 3),
                    E(ItemID.LifeforcePotion, 3, 1, 3)),

                Stage("postgolem", "石巨人后", "石巨人后到拜月教徒前，补甲壳、松露虫和可选事件资源。",
                    new UnlockConditions { Defeated = ["golem"], NotDefeated = ["cultist"] },
                    E(ItemID.BeetleHusk, 5, 4, 10),
                    E(ItemID.TruffleWorm, 3, 1, 2),
                    E(ItemID.LunarTabletFragment, 3, 4, 12),
                    E(ItemID.Picksaw, 1),
                    E(ItemID.GreaterHealingPotion, 4, 8, 20),
                    E(ItemID.EndurancePotion, 3, 1, 3),
                    E(ItemID.LifeforcePotion, 3, 1, 3)),

                Stage("lunar", "月总决战", "拜月教徒后到月总前，补碎片和月总召唤物。",
                    new UnlockConditions { Defeated = ["cultist"], NotDefeated = ["moonlord"] },
                    E(ItemID.FragmentSolar, 5, 6, 18),
                    E(ItemID.FragmentVortex, 5, 6, 18),
                    E(ItemID.FragmentNebula, 5, 6, 18),
                    E(ItemID.FragmentStardust, 5, 6, 18),
                    E(ItemID.CelestialSigil, 2),
                    E(ItemID.LunarHook, 1),
                    E(ItemID.GreaterHealingPotion, 4, 8, 20),
                    E(ItemID.GreaterManaPotion, 4, 8, 20),
                    E(ItemID.SuperHealingPotion, 3, 3, 8)),

                Stage("postmoonlord", "月亮领主后", "月亮领主后保留终局材料、恢复药水和采掘辅助，不再退回开荒池。",
                    new UnlockConditions { Defeated = ["moonlord"] },
                    E(ItemID.LunarOre, 6, 10, 30),
                    E(ItemID.FragmentSolar, 4, 8, 24),
                    E(ItemID.FragmentVortex, 4, 8, 24),
                    E(ItemID.FragmentNebula, 4, 8, 24),
                    E(ItemID.FragmentStardust, 4, 8, 24),
                    E(ItemID.SuperHealingPotion, 4, 5, 15),
                    E(ItemID.GreaterManaPotion, 3, 8, 20),
                    E(ItemID.SpelunkerPotion, 3, 2, 5),
                    E(ItemID.MiningPotion, 3, 2, 5))
            ]
        };
    }

    private static FishingLootStage Stage(string id, string name, string description, UnlockConditions unlock, params LootEntry[] items)
    {
        return new FishingLootStage
        {
            Id = id,
            Name = name,
            Description = description,
            Unlock = unlock,
            Items = items.ToList()
        };
    }

    private static LootEntry E(int itemId, int weight, int minStack = 1, int maxStack = 1)
    {
        return new LootEntry
        {
            ItemId = itemId,
            Weight = weight,
            MinStack = minStack,
            MaxStack = maxStack
        };
    }
}
